src/main/java/com/tr/cimsa/denetimtaleptakip/model/AuditType.java
package com.tr.cimsa.denetimtaleptakip.model;

import com.google.common.collect.Sets;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Set;

/**
 * User: mhazer
 * Date: 8/19/12
 * Time: 4:58 PM
 */
@Entity
@Table(name = "DT_ID_AUDIT_TYPE_TABLE")
@Data
@ToString(includeFieldNames = true, callSuper = true, exclude = {"businessProcessTypes", "auditTypeUpdateFollowers"})
@EqualsAndHashCode(callSuper = true, exclude = {"businessProcessTypes", "sendOpeningEmail", "emailSendingStrategy", "emailStrategyContentOne",
        "emailStrategyContentTwo","emailStrategyContentThree","updateEmailContent", "openingEmailContent", "auditTypeUpdateFollowers","sendWeeklyReminderMail"})
public class AuditType extends BaseDefinitionEntity implements Serializable
{
	public Set<BusinessProcessType> getBusinessProcessTypes() {
        return businessProcessTypes;
	}
	
	public List<BusinessProcessType> getBusinessProcessTypesSorted() {
		this.al.addAll(businessProcessTypes);
        if (this.al.size() > 0) {
             Collections.sort(this.al, new Comparator<BusinessProcessType>() {
                 @Override
                 public int compare(final BusinessProcessType object1, final BusinessProcessType object2) {
                     return object1.getDescription().compareTo(object2.getDescription());
                 }
             });
        }
		return this.al;
	}
	
	public void setBusinessProcessTypes(Set<BusinessProcessType> businessProcessTypes) {
		this.businessProcessTypes = businessProcessTypes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "DT_ID_AUDIT_BUSINESS_TABLE",
            joinColumns =
            @JoinColumn(name = "AUDIT_ID", referencedColumnName = "id"),
            inverseJoinColumns =
            @JoinColumn(name = "BUSINESS_TYPE_ID", referencedColumnName = "id")
    )
    private Set<BusinessProcessType> businessProcessTypes = Sets.newHashSet();
	
	@Transient
	private List<BusinessProcessType> al = new ArrayList<BusinessProcessType>();

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SEND_WEEKLY_REMINDER_MAIL")
    @NotFound(action = NotFoundAction.IGNORE)
    private EmailContent sendWeeklyReminderMail;
    
    @Column(name = "SEND_OPENING_MAIL", nullable = false, columnDefinition = "BIT", length = 1)
    private boolean sendOpeningEmail;

    @Column(name = "EMAIL_SUBJECT", nullable = false)
    private String emailSubject;

    @ManyToOne
    @JoinColumn(name = "EMAIL_SENDING_STRATEGY")
    private EmailSendingStrategy emailSendingStrategy;

    @Column(name="MAXIMUM_REVISED_DATE")
    private String maximumRevisedDate;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMAIL_STRATEGY_CONTENT_ONE_ID")
    @NotFound(action = NotFoundAction.IGNORE)
    private EmailContent emailStrategyContentOne;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMAIL_STRATEGY_CONTENT_TWO_ID")
    @NotFound(action = NotFoundAction.IGNORE)
    private EmailContent emailStrategyContentTwo;

    @ManyToOne
    @JoinColumn(name = "UPDATE_EMAIL_CONTENT_ID")
    @NotFound(action = NotFoundAction.IGNORE)
    private EmailContent updateEmailContent;

    @ManyToOne
    @JoinColumn(name = "OPENING_EMAIL_CONTENT_ID")
    @NotFound(action = NotFoundAction.IGNORE)
    private EmailContent openingEmailContent;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMAIL_STRATEGY_CONTENT_THREE_ID")
    @NotFound(action = NotFoundAction.IGNORE)
    private EmailContent emailStrategyContentThree;

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "DT_ID_AUDIT_TYP_FOLLOWER_TABLE",
            joinColumns =
            @JoinColumn(name = "AUDIT_TYPE_ID", referencedColumnName = "id"),
            inverseJoinColumns =
            @JoinColumn(name = "USER_ID", referencedColumnName = "id")
    )
    @NotFound(action = NotFoundAction.IGNORE)
    private Set<User> auditTypeUpdateFollowers = Sets.newHashSet();

    @Transient
    public List<User> getResponsibleHeadsAsList()
    {
        return Collections.emptyList();
    }

    @Column(name = "COMPANY_REQUIRED", nullable = false, columnDefinition = "BIT", length = 1)
    private boolean companyRequired;

    @Transient
    public boolean getCompanyRequired()
    {
        return companyRequired;
    }
}

src/main/java/com/tr/cimsa/denetimtaleptakip/model/User.java
package com.tr.cimsa.denetimtaleptakip.model;

import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import org.apache.commons.collections.CollectionUtils;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.envers.RelationTargetAuditMode;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * User: dpinar
 * Date: 3/8/17
 * Time: 3:27 PM
 */

@Entity
@Table(name = "dt_id_users_table")
@Data
@ToString(includeFieldNames = true, callSuper = true, exclude = {"findings", "adminUser", "responsibleBusinessTypes", "responsibleBusinessSubTypes"})
@EqualsAndHashCode(callSuper = true, of = {"username"})
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
public class User extends BaseEntity implements Serializable
{ 
    @Column(name = "username")
    private String username;
    @Column(name = "email")
    private String email;
    @Column(name = "name_surname")
    private String nameSurname;
    @Column(name = "job_title")
    private String jobTitle;
    @Column(name = "ACTIVE", columnDefinition = "BIT", length = 1)
    private boolean active = true;
    @ManyToOne
    @JoinColumn(name = "ADMIN_USER_ID")
    private User adminUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EDIT_DATE")
    private Date editDate;

    @OneToMany(mappedBy = "actionOwner")
    private Set<FindingAction> findings = Sets.newHashSet();

    @ManyToMany(mappedBy = "responsibleHeads", fetch = FetchType.LAZY)
    private Set<BusinessProcessType> responsibleBusinessTypes = Sets.newHashSet();

    @ManyToMany(mappedBy = "responsibleHeads", fetch = FetchType.LAZY)
    private Set<BusinessSubProcessType> responsibleBusinessSubTypes = Sets.newHashSet();

    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinTable(
            name = "DT_ID_USER_ROLES_TABLE",
            joinColumns =
            @JoinColumn(name = "USER_ID", referencedColumnName = "id"),
            inverseJoinColumns =
            @JoinColumn(name = "ROLE_ID", referencedColumnName = "id")
    )
    @Fetch(FetchMode.SUBSELECT)
    @NotAudited
    private Set<Role> roles = Sets.newHashSet();

    @Transient
    public static List<String> usersEmailAddresses(Collection<User> users)
    {
        List<String> emailAddresses = Lists.newArrayList();
        for (User user : users)
        {
        	if(user.isActive())	// kullanıcı aktif ise mail listesine ekle 
        		emailAddresses.add(user.getEmail());
        }
        return emailAddresses;
    }

    @Transient
    public static List<String> usersNamesAndSurnames(Collection<User> users)
    {
        List<String> namesAndSurname = Lists.newArrayList();
        for (User user : users)
        {
            namesAndSurname.add(user.getNameSurname());
        }
        return namesAndSurname;
    }

    @Transient
    public boolean isUserReponsibleOfAnyBusinessType()
    {
        return CollectionUtils.isNotEmpty(getResponsibleBusinessTypes()) || CollectionUtils.isNotEmpty(getResponsibleBusinessSubTypes());
    }

    @Transient
    public boolean hasRole(String roleName)
    {
        for (Role role : getRoles())
        {
            if (role.getName().equals(roleName))
            {
                return true;
            }
        }
        return false;
    }

    @Transient
    public List<Role> getRolesAsList()
    {
        return Lists.newLinkedList(getRoles());
    }

}

src/main/java/com/tr/cimsa/denetimtaleptakip/controller/admin/FindingGraphicalReportsController.java
package com.tr.cimsa.denetimtaleptakip.controller.admin;

import com.google.common.collect.Lists;
import com.tr.cimsa.denetimtaleptakip.model.Finding;
import com.tr.cimsa.denetimtaleptakip.model.Status;

import lombok.Getter;
import org.primefaces.event.ItemSelectEvent;
import org.primefaces.model.chart.PieChartModel;
import org.springframework.beans.factory.annotation.Autowired;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;

/**
 * User: mhazer
 * Date: 8/30/12
 * Time: 11:21 PM
 */
@ManagedBean(name = "findingGraphicalReportsController")
@RequestScoped
public class FindingGraphicalReportsController extends BaseAdminController implements Serializable
{

    @Getter
    private PieChartModel pieChartModel;
    
    @PostConstruct
    public void init()
    {
    	List<Finding> findings = this.findingService.retrieveAllFindings();
        pieChartModel = preparePieChart(findings);
    }

    public static PieChartModel preparePieChart(List<Finding> findings)
    {
        PieChartModel _pieChartModel = new PieChartModel();
        for (Finding finding : findings)
        {
            Status findingStatus = finding.getStatus();
            if (_pieChartModel.getData().get(findingStatus.getDescription()) == null)
            {
                _pieChartModel.set(findingStatus.getDescription(), 1);
            }
            else
            {
                Number oldValue = _pieChartModel.getData().get(findingStatus.getDescription());
                Number newValue = (oldValue.intValue()) + 1;
                _pieChartModel.set(findingStatus.getDescription(), newValue);
            }
        }
        return _pieChartModel;
    }

    public void selectPieChart(ItemSelectEvent event) throws IOException
    {
        String statusOfSelectedChartItem = Lists.newLinkedList(pieChartModel.getData().entrySet()).get(event.getItemIndex()).getKey();
        logger.debug("clicked chart item is {}", statusOfSelectedChartItem);
        FacesContext.getCurrentInstance().getExternalContext().redirect("/" + FacesContext.getCurrentInstance().getExternalContext().getContextName() + "/admin/searchFinding.xhtml?status=" + Status.findStatusFromDescription(statusOfSelectedChartItem));
    }

    @Override
    protected Class getClazz()
    {
        return FindingGraphicalReportsController.class;
    }
}

src/main/java/com/tr/cimsa/denetimtaleptakip/controller/admin/NumberOfFindingsPerCompanyGraphicalReportController.java
package com.tr.cimsa.denetimtaleptakip.controller.admin;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;

import org.primefaces.event.ItemSelectEvent;
import org.primefaces.model.chart.PieChartModel;

import com.google.common.collect.Lists;
import com.tr.cimsa.denetimtaleptakip.controller.util.FacesUtils;
import com.tr.cimsa.denetimtaleptakip.model.AuditType;
import com.tr.cimsa.denetimtaleptakip.model.Company;
import com.tr.cimsa.denetimtaleptakip.model.Finding;

import lombok.Getter;
import lombok.Setter;

/**
 * User: mhazer Date: 8/30/12 Time: 11:21 PM
 */
@ManagedBean(name = "numberOfFindingsPerCompanyGraphicalReportController")
@ViewScoped
public class NumberOfFindingsPerCompanyGraphicalReportController extends BaseAdminController implements Serializable {

	@Getter
	private PieChartModel pieChartModel;

	@Getter
	@Setter
	private List<AuditType> selectedAuditTypes = Lists.newArrayList();

	private List<Finding> selectedFindings;

	@PostConstruct
	public void init() {		
		try {
			List<AuditType> myAuditTypes = commonDefinitionsController.getAuditTypes();

			int minId = this.findMinId(findingService.retrieveAuditTypes());

			List<Finding> mySelectedFindings = new LinkedList<Finding>();

			for (AuditType auditType : myAuditTypes) {

				if (auditType.getId() == minId) {
					SearchParameters searchParameters = new SearchParameters();
					List<AuditType> atlist = new ArrayList<>();
					atlist.add(auditType);
					searchParameters.setAuditTypes(atlist);
					mySelectedFindings.addAll(findingService.searchFindings(searchParameters));
					preparePieChartOfThis(mySelectedFindings);
					selectedAuditTypes.add(auditType);
					break;
				}

			}
		} catch (Exception e) {
			e.printStackTrace();
			logger.debug("init Exception :"+e.getMessage());
		}
	}

	private PieChartModel initPieChartModel() {
		pieChartModel = new PieChartModel();
		pieChartModel.setResetAxesOnResize(true);
		pieChartModel.setLegendPosition("ne");
	
//		pieChartModel.setSeriesColors("ff0000,ffa500,ffff00,9acd32");
		return pieChartModel;
	}

	public void changeAuditType() {
		try {
			SearchParameters searchParameters = new SearchParameters();
			searchParameters.setAuditTypes(selectedAuditTypes);
			selectedFindings = findingService.searchFindings(searchParameters);
			preparePieChartOfThis(selectedFindings);

		} catch (Exception e) {
			System.err.println(e);
			FacesUtils.addMessage(FacesMessage.SEVERITY_ERROR, e.getMessage(), null);
		}
	}

	private PieChartModel preparePieChartOfThis(List<Finding> findings) {
		PieChartModel _pieChartModel = initPieChartModel();
		for (Finding finding : findings) {
			Company company = finding.getCompany();
			String companyName = company != null ? company.getDescription() : "ŞİRKET BELİRTİLMEMİŞ";

			if (_pieChartModel.getData().get(companyName) == null) {
				_pieChartModel.set(companyName, 1);
			} else {
				Number oldValue = _pieChartModel.getData().get(companyName);
				Number newValue = (oldValue.intValue()) + 1;
				_pieChartModel.set(companyName, newValue);
				_pieChartModel.setShowDatatip(true);
			     
				_pieChartModel.setShowDataLabels(true);
				     
				_pieChartModel.setDataFormat("value");
			}
		}
		return _pieChartModel;
	}

	public static PieChartModel preparePieChart(List<Finding> findings) {
		PieChartModel _pieChartModel = new PieChartModel();
		for (Finding finding : findings) {
			Company company = finding.getCompany();
			String companyName = company != null ? company.getDescription() : "ŞİRKET BELİRTİLMEMİŞ";

			if (_pieChartModel.getData().get(companyName) == null) {
				_pieChartModel.set(companyName, 1);
			} else {
				Number oldValue = _pieChartModel.getData().get(companyName);
				Number newValue = (oldValue.intValue()) + 1;
				_pieChartModel.set(companyName, newValue);
			}

		}
		return _pieChartModel;
	}

	public void selectPieChart(ItemSelectEvent event) throws IOException {
		String companyOfSelectedChartItem = Lists.newLinkedList(pieChartModel.getData().entrySet())
				.get(event.getItemIndex()).getKey();
		logger.debug("clicked chart item is {}", companyOfSelectedChartItem);

		Flash flash = FacesContext.getCurrentInstance().getExternalContext().getFlash();
		flash.put("companyName", companyOfSelectedChartItem);
		flash.put("selectedAuditTypes", selectedAuditTypes);

		logger.debug("clicked chart item is {}", companyOfSelectedChartItem);
		FacesContext.getCurrentInstance().getExternalContext()
				.redirect(FacesContext.getCurrentInstance().getExternalContext().getRequestContextPath()
						+ "/admin/searchFinding.xhtml?faces-redirect=true");

	}

	@Override
	protected Class getClazz() {
		return NumberOfFindingsPerCompanyGraphicalReportController.class;
	}
	
	public Integer findMinId(List<AuditType> list) { 
		List<Integer> idList = new ArrayList<Integer>();
		
		if (list != null || list.size() != 0) {
			for (AuditType at : list)
				idList.add(at.getId());
			return Collections.min(idList);
        }
	
		return null;
    }
}

src/main/webapp/admin/auditAndBusinessTypesViewAll.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:prime="http://primefaces.org/ui"
                xmlns:util="http://java.sun.com/jsf/composite/components/common"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="pageHeader">
        View All Audit, Business and Business Process Types in Once
    </ui:define>

    <ui:define name="mainContent">
        <h:form>
            <prime:commandButton value="Print" type="button" icon="ui-icon-print" style="float:right">
                <prime:printer target="tree"/>
            </prime:commandButton>
            <br />
            <br />
            <prime:treeTable
                    id="tree"
                    value="#{auditBusinessTypeController.rootNode}"
                    var="_node"
                    dynamic="true"
                    cache="false">
                <prime:column headerText="Description">
                    <h:outputText value="#{_node.description}"/>
                </prime:column>
                <prime:column headerText="Responsible Heads">
                    <prime:dataList value="#{_node.responsibleHeadsAsList}" var="_responsible" styleClass="dataList">
                        #{_responsible.nameSurname}
                    </prime:dataList>
                </prime:column>
            </prime:treeTable>
            <br />
            <prime:commandButton value="Print" type="button" icon="ui-icon-print" style="float:right">
                <prime:printer target="tree"/>
            </prime:commandButton>
        </h:form>
    </ui:define>

    <ui:define name="helpContent">
        <b>
        </b>
    </ui:define>

</ui:composition>

src/main/webapp/admin/findingAdmin.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:prime="http://primefaces.org/ui"
                xmlns:util="http://java.sun.com/jsf/composite/components/common"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="pageHeader">
        Audit Findings
    </ui:define>

    <ui:define name="mainContent">
        <h:form id="findingAdminId">
            <util:findingList
                    findings="#{findingAdminController.findingLazyDataModel}"
                    activeActionOwners="#{findingAdminController.findingLazyDataModel.actionOwnersOfFindings}"
                    activeResponsibleOwners="#{findingAdminController.findingLazyDataModel.responsibleOwnersOfFindings}"
                    statuses="#{searchFindingController.searchParameters.getStatusDescriptions()}"
                    bean="#{findingAdminController}"
                   />
        </h:form>
    </ui:define>

    <ui:define name="helpContent">
        <b>
            At this page you can view the audit findings that are assigned to you and other users and also view/change status of them
        </b>
    </ui:define>

</ui:composition>

src/main/webapp/admin/userAdmin.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:prime="http://primefaces.org/ui"
                xmlns:util="http://java.sun.com/jsf/composite/components/common"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="pageHeader">
        User Administration
    </ui:define>

    <ui:define name="mainContent">
        <h:form id="userAdminForm">
            <prime:commandButton
                    value="Add new user"
                    styleClass="btn btn-primary btn-small"
                    style="float:right"
                    process="@this"
                    actionListener="#{userAdminController.addNewUser()}"
                    oncomplete="PF('dialogAddEditUser').show();"/>
            <br/>
            <br/>
            <br/>
            <prime:dataTable value="#{commonDefinitionsController.allUsers}" var="_user" id="usersDataTable">
                <prime:column headerText="Username" sortBy="#{_user.username}" filterBy="#{_user.username}" filterMatchMode="contains">
                    <h:outputText value="#{_user.username}"/>
                </prime:column>
                <prime:column headerText="Name and Surname" sortBy="#{_user.nameSurname}" filterBy="#{_user.nameSurname}" filterMatchMode="contains">
                    <h:outputText value="#{_user.nameSurname}"/>
                </prime:column>
                <prime:column headerText="Email" sortBy="#{_user.email}" filterBy="#{_user.email}" filterMatchMode="contains">
                    <h:outputText value="#{_user.email}"/>
                </prime:column>
                <prime:column headerText="Job Title" sortBy="#{_user.jobTitle}" filterBy="#{_user.jobTitle}" filterMatchMode="contains">
                    <h:outputText value="#{_user.jobTitle}"/>
                </prime:column>
                <prime:column headerText="Active" sortBy="#{_user.active}" style="text-align:center">
                    <h:outputText value="#{_user.active ? 'Active' : 'Deactive'}" style="color: #{_user.active ? 'green' : 'red'}"/>
                </prime:column>
                <prime:column headerText="Roles" style="text-align:center">
                    <prime:dataList value="#{_user.rolesAsList}" var="_role" styleClass="dataList">
                        #{_role.name}
                    </prime:dataList>
                </prime:column>
                <prime:column width="30" style="text-align:center">
                    <prime:commandButton
                            title="Edit"
                            style="float:left"
                            actionListener="#{userAdminController.selectUser(_user)}"
                            onsuccess="PF('dialogAddEditUser').show();"
                            icon="ui-icon-pencil"/>
                </prime:column>
            </prime:dataTable>
            <br/>

            <prime:commandButton
                    value="Add new user"
                    styleClass="btn btn-primary btn-small"
                    style="float:right"
                    process="@this"
                    actionListener="#{userAdminController.addNewUser()}"
                    oncomplete="PF('dialogAddEditUser').show();"/>

        </h:form>

        <h:form id="userSaveForm">
            <prime:dialog id="dialogAddEditUser" closable="false" widgetVar="dialogAddEditUser" header="Edit/Add User" dynamic="true" modal="true">
                <prime:outputPanel autoUpdate="true">
                    <h:panelGrid columns="2" styleClass="table table-striped table-bordered table-condensed">

                        <prime:outputLabel value="Username:" for="txtUsername"/>
                        <prime:inputText id="txtUsername" value="#{userAdminController.selectedUser.username}" required="true" requiredMessage="Username is required"/>

                        <prime:outputLabel value="Name and Surname:" for="txtNameAndSurname"/>
                        <prime:inputText id="txtNameAndSurname" value="#{userAdminController.selectedUser.nameSurname}" required="true"
                                         requiredMessage="Name and Surname is required"/>

                        <prime:outputLabel value="Email:" for="txtEmail"/>
                        <prime:inputText id="txtEmail" value="#{userAdminController.selectedUser.email}" required="true" requiredMessage="Email is required" size="200"
                                         validatorMessage="Please enter valid email">
                            <f:validateRegex pattern="^[_A-Za-z0-9-]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*(\.[_A-Za-z0-9-]+)"/>
                        </prime:inputText>

                        <prime:outputLabel value="Job Title:" for="txtJobTitle"/>
                        <prime:inputText id="txtJobTitle" value="#{userAdminController.selectedUser.jobTitle}" required="true" requiredMessage="Job title is required"/>

                        <h:outputText value="Active:"/>
                        <prime:selectBooleanCheckbox value="#{userAdminController.selectedUser.active}"/>

                        <prime:outputLabel for="txtUserRoles" value="User Role(s):"/>
                        <h:panelGroup styleClass="aksPickList">
                            <prime:pickList
                                    id="txtUserRoles"
                                    value="#{userAdminController.selectedUserRoles}"
                                    var="_userRole"
                                    itemValue="#{_userRole}"
                                    itemLabel="#{_userRole.name}"
                                    showSourceControls="false" showTargetControls="false"
                                    converter="roleConverter"
                                    required="true"
                                    requiredMessage="At least one role must be chosen">
                                <f:facet name="sourceCaption">Available</f:facet>
                                <f:facet name="targetCaption">Assigned</f:facet>
                                <f:attribute name="roleEntities" value="#{commonDefinitionsController.allRoles}"/>
                            </prime:pickList>
                        </h:panelGroup>

                        <f:facet name="footer">
                            <h:panelGroup style="float:right;">
                                <prime:commandButton value="Cancel" onsuccess="PF('dialogAddEditUser').hide();" process="@this"/>
                                <prime:commandButton
                                        value="Save"
                                        actionListener="#{userAdminController.saveUser()}"
                                        update=":userAdminForm:usersDataTable, :growl"
                                        oncomplete="handleSaveUserRequest(xhr, status, args)"/>
                            </h:panelGroup>
                        </f:facet>
                    </h:panelGrid>
                </prime:outputPanel>
            </prime:dialog>
        </h:form>
        <script type="text/javascript">
            function handleSaveUserRequest(xhr, status, args)
            {
                if (args.validationFailed)
                {
                    jQuery('#dialogAddEditUser').effect("shake", { times:3 }, 100);
                }
                else
                {
                	PF('dialogAddEditUser').hide();
                }
            }
        </script>
    </ui:define>

    <ui:define name="helpContent">
        <b>
        </b>
    </ui:define>

</ui:composition>