src/main/java/com/tr/cimsa/denetimtaleptakip/model/User.java
package com.tr.cimsa.denetimtaleptakip.model;

import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import org.apache.commons.collections.CollectionUtils;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.envers.RelationTargetAuditMode;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * User: dpinar
 * Date: 3/8/17
 * Time: 3:27 PM
 */

@Entity
@Table(name = "dt_id_users_table")
@Data
@ToString(includeFieldNames = true, callSuper = true, exclude = {"findings", "adminUser", "responsibleBusinessTypes", "responsibleBusinessSubTypes"})
@EqualsAndHashCode(callSuper = true, of = {"username"})
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
public class User extends BaseEntity implements Serializable
{ 
    @Column(name = "username")
    private String username;
    @Column(name = "email")
    private String email;
    @Column(name = "name_surname")
    private String nameSurname;
    @Column(name = "job_title")
    private String jobTitle;
    @Column(name = "ACTIVE", columnDefinition = "BIT", length = 1)
    private boolean active = true;
    @ManyToOne
    @JoinColumn(name = "ADMIN_USER_ID")
    private User adminUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EDIT_DATE")
    private Date editDate;

    @OneToMany(mappedBy = "actionOwner")
    private Set<FindingAction> findings = Sets.newHashSet();

    @ManyToMany(mappedBy = "responsibleHeads", fetch = FetchType.LAZY)
    private Set<BusinessProcessType> responsibleBusinessTypes = Sets.newHashSet();

    @ManyToMany(mappedBy = "responsibleHeads", fetch = FetchType.LAZY)
    private Set<BusinessSubProcessType> responsibleBusinessSubTypes = Sets.newHashSet();

    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinTable(
            name = "DT_ID_USER_ROLES_TABLE",
            joinColumns =
            @JoinColumn(name = "USER_ID", referencedColumnName = "id"),
            inverseJoinColumns =
            @JoinColumn(name = "ROLE_ID", referencedColumnName = "id")
    )
    @Fetch(FetchMode.SUBSELECT)
    @NotAudited
    private Set<Role> roles = Sets.newHashSet();

    @Transient
    public static List<String> usersEmailAddresses(Collection<User> users)
    {
        List<String> emailAddresses = Lists.newArrayList();
        for (User user : users)
        {
        	if(user.isActive())	// kullanıcı aktif ise mail listesine ekle 
        		emailAddresses.add(user.getEmail());
        }
        return emailAddresses;
    }

    @Transient
    public static List<String> usersNamesAndSurnames(Collection<User> users)
    {
        List<String> namesAndSurname = Lists.newArrayList();
        for (User user : users)
        {
            namesAndSurname.add(user.getNameSurname());
        }
        return namesAndSurname;
    }

    @Transient
    public boolean isUserReponsibleOfAnyBusinessType()
    {
        return CollectionUtils.isNotEmpty(getResponsibleBusinessTypes()) || CollectionUtils.isNotEmpty(getResponsibleBusinessSubTypes());
    }

    @Transient
    public boolean hasRole(String roleName)
    {
        for (Role role : getRoles())
        {
            if (role.getName().equals(roleName))
            {
                return true;
            }
        }
        return false;
    }

    @Transient
    public List<Role> getRolesAsList()
    {
        return Lists.newLinkedList(getRoles());
    }

}

src/main/webapp/WEB-INF/templates/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:prime="http://primefaces.org/ui"
	xmlns:sec="http://www.springframework.org/security/tags">
<h:head>

	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Pragma" content="no-cache" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta http-equiv="Expires" content="0" />
	<meta http-equiv="Last-Modified" content="0" />
	<meta http-equiv="Cache-Control" content="no-cache, mustrevalidate" />
	<title><ui:insert name="title">Çimsa Audit Follow Up System (AFUS)</ui:insert></title>
	<link
		href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap.css"
		rel="stylesheet" type="text/css" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap-responsive.min.css"
		rel="stylesheet" type="text/css" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap-aks.css"
		rel="stylesheet" type="text/css" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/favicon.ico"
		rel="icon" />
	<script
		src="#{facesContext.externalContext.requestContextPath}/style/js/bootstrap.min.js"
		type="text/javascript"></script>
		<script>
        function extender() {
        this.cfg.seriesDefaults = {
        showMarker: true,
        renderer: $.jqplot.BarRenderer,
        pointLabels: {show: true, location: 'n', ypadding: 0, hideZeros: true}
        };    
    }
</script>
		
	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"
		type="text/javascript"></script>
	<!-- <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script> -->
	<style>
		.affaires .ui-menuitem-text {
			color: #f5f5f5;
			font-weight: bold;
		}
		
		.affaires .ui-widget-content {
			background: #0d3a88;
		}
		
		.container-fluid {
			padding-left: 0px !important;
			padding-right: 0px !important;
		}
		.ui-datatable-odd{
			background-color:#ecf4ff !important;
		}
		label{
		  font-size:12px !important;
		}
		.ui-selectmanycheckbox{
			float:left !important;
		}
	</style>
	<script>
		$(document).ready(function(){
			$("option").each(function() {
				if(this.text=="*"){
					$(this).html("All");
				}
			});
		});
	</script>
</h:head>

<body>

	<div class="navbar navbar-fixed-top">
		<div class="container-fluid">
			<h:form>
				<div class="nav-collapse collapse">
					<prime:menubar style="background: #0d3a88">

						<prime:menuitem styleClass="brand"
							style="margin-left: 1px; margin-bottom: 1px; margin-right:16px;"
							value="Çimsa Audit Follow Up System (AFUS)"
							action="#{authenticationController.redirectUserToWelcomePage}" />

						<prime:menuitem value="My Tasks"
							rendered="#{sec:areAnyGranted('ROLE_USER')}"
							url="/users/userTasks.xhtml"
							style="margin: auto; margin-top: 5px; color: #f5f5f5; font-weight: bold; font-size: 14px;" />

						<prime:menuitem value="My Department Tasks"
							rendered="#{sec:areAnyGranted('ROLE_USER, ROLE_ADMIN') and visit.user.userReponsibleOfAnyBusinessType}"
							url="/users/departmentFindings.xhtml"
							style="margin: auto; margin-top: 5px; color: #f5f5f5; font-weight: bold; font-size: 14px;" />

						<prime:menuitem value="Finding List"
							rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_READONLY')}"
							url="/admin/findingAdmin.xhtml"
							style="margin: auto; margin-top: 5px; color: #f5f5f5; font-weight: bold; font-size: 14px;" />

						<prime:menuitem value="Search" url="/admin/searchFinding.xhtml"
							rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_USER, ROLE_READONLY')}"
							style="margin: auto; margin-top: 5px; color: #f5f5f5; font-weight: bold; font-size: 14px;"
							action="#{commonDefinitionsController.init()}" />

						<prime:submenu label="Finding" styleClass="affaires"
							rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
							style="margin: auto; margin-top: 5px; font-size: 14px;">
							<prime:menuitem value="New"
								rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
								url="/admin/editFinding.xhtml" style="font-size: 14px"/>
							<prime:menuitem value="Excel Import"
								rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
								url="/admin/importFinding.xhtml" style="font-size: 14px"/>
						</prime:submenu>

						<prime:submenu label="Administration" styleClass="affaires"
							rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
							style="margin: auto; margin-top: 5px; font-size: 14px;">
							<prime:menuitem value="User Administration"
								rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
								url="/admin/userAdmin.xhtml" style="font-size: 14px"/>

							<prime:submenu label="Audit and Main Process Administration" style="font-size: 14px">
								<prime:menuitem value="Audit Type Administration"
									rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
									url="/admin/auditTypesAdmin.xhtml" style="font-size: 14px"/>
								<prime:menuitem value="Main Process Administration"
									rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
									url="/admin/businessTypesAdmin.xhtml" style="font-size: 14px"/>
								<prime:menuitem value="View All in Once"
									rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
									url="/admin/auditAndBusinessTypesViewAll.xhtml" style="font-size: 14px"/>
							</prime:submenu>
							<prime:menuitem value="Department Administration"
								rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
								url="/admin/departmentTypesAdmin.xhtml" style="font-size: 14px"/>
							<prime:menuitem value="Email Administration"
								rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
								url="/admin/emailAdmin.xhtml" style="font-size: 14px"/>
						</prime:submenu>

						<prime:submenu label="Reports" styleClass="affaires"
							rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
							style="margin: auto; margin-top: 5px; font-size: 14px;">
							<prime:menuitem value="Number of Findings per Status Graph"
								rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_READONLY')}"
								url="/admin/numberOfFindingsPerStatusGraphicalReport.xhtml" style="font-size: 14px"/>
							<prime:menuitem value="Number of Findings per Company Graph"
								rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_READONLY')}"
								url="/admin/numberOfFindingsPerCompanyGraphicalReport.xhtml" style="font-size: 14px"/>
							<prime:menuitem value="Number of Findings per Year Graph"
								rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_READONLY')}"
								url="/admin/numberOfFindingsPerYearGraphicalReport.xhtml" style="font-size: 14px"/>
						</prime:submenu>

						<prime:menuitem value="Help"
							rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_USER, ROLE_READONLY')}"
							style="margin: auto; margin-top: 5px; color: #f5f5f5; font-weight: bold; font-size: 14px;"
							url="/documents/Help_Dokumani.pdf" target="_document" />

						<prime:menuitem
							style="position: absolute; top: 9px; right: 6px; color: #f5f5f5; font-weight: bold; font-size: 14px;"
							value="Logout (#{visit.user.nameSurname})"
							action="#{authenticationController.logout}" />

					</prime:menubar>
				</div>
			</h:form>
		</div>
	</div>


	<prime:growl id="growl" showDetail="false" sticky="false" life="5000"
		autoUpdate="true" />


	<prime:ajaxStatus onstart="PF('statusDialog').show()"
		oncomplete="PF('statusDialog').hide()" />

	<prime:dialog modal="false" widgetVar="statusDialog"
		header="Please Wait" draggable="false" closable="false"
		showEffect="bounce" hideEffect="bounce" resizable="false">
		<prime:graphicImage value="/images/ajaxloadingbar.gif" />
	</prime:dialog>

	<!-- /container -->

	<div class="container">

		<div class="content">
			<div class="page-header">
				<h5>
					<ui:insert name="pageHeader" />
				</h5>
			</div>
			<div class="row">
				<div class="span12">
					<ui:insert name="mainContent" />
				</div>
			</div>
		</div>

		<footer>
		<p>
			Bu sistemin mülkiyeti Çimsa’ya aittir ve şirkete özel, gizli bilgiler
			içermektedir. Bu bilgiler Çimsa dışı kullanılamaz ve paylaşılamaz.
			Bilgi güvenliği ve gizliliği kullanıcıların sorumluluğundadır.
			<br />
			This system belongs to Çimsa and contains private, confidential
			informations. These informations can not be shared or disclosed outside
			the Company. Information security and confidentiality are under the
			responsibility of system users.
		</p>
		</footer>

	</div>
	<!-- /container -->
</body>
</html>

src/main/webapp/WEB-INF/templates/noLinksTemplateForAccessDenied.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:prime="http://primefaces.org/ui">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Pragma" content="no-cache" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta http-equiv="Expires" content="0" />
	<meta http-equiv="Last-Modified" content="0" />
	<meta http-equiv="Cache-Control" content="no-cache, mustrevalidate" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title><ui:insert name="title">Çimsa Audit Follow Up System (AFUS) v#{initParam['appVersion']}</ui:insert></title>
	<link
		href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap.css"
		rel="stylesheet" type="text/css" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap-responsive.min.css"
		rel="stylesheet" type="text/css" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap-aks.css"
		rel="stylesheet" type="text/css" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/favicon.ico"
		rel="icon" />
	<script
		src="#{facesContext.externalContext.requestContextPath}/style/js/bootstrap.min.js"
		type="text/javascript"></script>
	<!-- <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script> -->
	<style>
		.container-fluid {
			padding-left:0px !important;
			padding-right:0px !important;
		}
	</style>
</h:head>

<body>
	<div class="navbar navbar-fixed-top">
		<div class="container-fluid">
			<h:form>
				<div class="nav-collapse collapse">
					<prime:menubar style="background: #0d3a88">

						<prime:menuitem styleClass="brand"
							style="margin-left: 1px; margin-bottom: 1px;"
							value="Çimsa Audit Follow Up System (AFUS) v#{initParam['appVersion']}"
							action="#{authenticationController.redirectUserToWelcomePage}" />
							
						<prime:menuitem
							style="position: absolute; top: 9px; right: 6px; color: #f5f5f5; font-weight: bold;"
							value="Logout (#{visit.user.nameSurname})"
							action="#{authenticationController.logout}" />
						
					</prime:menubar>
				</div>
			</h:form>
		</div>
	</div>

	<prime:growl id="growl" showDetail="false" sticky="false" life="1500" />

	<!-- /container -->

	<div class="container">

		<div class="content">
			<div class="row">
				<div class="span2 offset4">
					<h:form>
						<ui:insert name="mainContent" />
					</h:form>
				</div>
			</div>
		</div>

		<footer>
		<p>Çimsa 2019</p>
		</footer>

	</div>
	<!-- /container -->
</body>
</html>

src/main/webapp/WEB-INF/templates/noLinksTemplateForLogin.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:prime="http://primefaces.org/ui">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Pragma" content="no-cache" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta http-equiv="Expires" content="0" />
	<meta http-equiv="Last-Modified" content="0" />
	<meta http-equiv="Cache-Control" content="no-cache, mustrevalidate" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title><ui:insert name="title">Çimsa Audit Follow Up System (AFUS) v#{initParam['appVersion']}</ui:insert></title>
	<link
		href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap.css"
		rel="stylesheet" type="text/css" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap-responsive.min.css"
		rel="stylesheet" type="text/css" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap-aks.css"
		rel="stylesheet" type="text/css" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/favicon.ico"
		rel="icon" />
	<script
		src="#{facesContext.externalContext.requestContextPath}/style/js/bootstrap.min.js"
		type="text/javascript"></script>
	<!-- <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script> -->
	<style>
		.container-fluid {
			padding-left:0px !important;
			padding-right:0px !important;
		}
	</style>
</h:head>

<body>
	<div class="navbar navbar-fixed-top">
		<div class="container-fluid">
			<h:form>
				<div class="nav-collapse collapse">
					<prime:menubar style="background: #0d3a88">

						<prime:menuitem styleClass="brand"
							style="margin-left: 1px; margin-bottom: 1px;"
							value="Çimsa Audit Follow Up System (AFUS) v#{initParam['appVersion']}"
							action="#{authenticationController.redirectUserToWelcomePage}" />
						
					</prime:menubar>
				</div>
			</h:form>
		</div>
	</div>

	<prime:growl id="growl" showDetail="false" sticky="false" life="1500"/>

	<!-- /container -->

	<div class="container">

		<div class="content">
			<div class="row">
				<div class="span2 offset4">
					<h:form>
						<ui:insert name="mainContent" />
					</h:form>
				</div>
			</div>
		</div>

		<footer>
		<p>Çimsa 2019</p>
		</footer>

	</div>
	<!-- /container -->
</body>
</html>